title: Webnovels
description: Read peak webnovels translated by me!
theme: minima

header_pages:
  - index.md

# Adicione esta linha para aplicar o estilo em todas as páginas:
plugins:
  - jekyll-feed
