title: Minhas Histórias
description: Leia minhas webnovels e capítulos aqui.
theme: minima

header_pages:
  - index.md

# Adicione esta linha para aplicar o estilo em todas as páginas:
plugins:
  - jekyll-feed
